### ISSUE TITLE
app store更新bob以后popclip无法调出bob

### ISSUE THREAD

**Issue by Dx-wmc** [ripperhe/bob-popclip#7]
今天突然发现app store更新了bob，然后popclip就无法调出bob了

**Comment by ripperhe** [comment]
你好，请问是用的 Bob 官网最新版的 PopClip 插件吗？具体的报错提示是什么？

**Comment by Dx-wmc** [comment]
选择一段文字以后会弹出一个叉号，我用bob的快捷键是能正常取词的

**Comment by Dx-wmc** [comment]
> 你好，请问是用的 Bob 官网最新版的 PopClip 插件吗？具体的报错提示是什么？

使用popclip的时候选择一段文字以后会弹出一个叉号，我用bob的快捷键是能正常取词。
用的是最新的插件，但是今天bob我发现有更新

**Comment by ripperhe** [comment]
PopClip 插件是 Bob v2 对吧？

**Comment by Dx-wmc** [comment]
> PopClip 插件是 Bob v2 对吧？

对的 bob v2在今天app store更新前还运行正常的，所以怀疑是bob的最新版与popclip不兼容？目前bob版本是1.7.1

popclip会出现这个样子
<img width="60" alt="image" src="https://user-images.githubusercontent.com/63085833/230779094-f67799be-e824-477e-9420-8fa71a5f51bd.png">

**Comment by ripperhe** [comment]
最近没改，是兼容的，我也这么用的，不然肯定大批量报反馈了。建议参考这篇文章：
https://bobtranslate.com/faq/popclip-error.html

**Comment by Dx-wmc** [comment]
使用命令行更新以后又可以了，看来是我电脑问题，感谢！

**Comment by ripperhe** [comment]
好的，不客气
