### ISSUE TITLE
Request to add Bob extension to PopClip Extensions Directory

### ISSUE THREAD

**Issue by pilotmoon** [ripperhe/bob-popclip#9]
Hello, I am Nick Moore, the developer of PopClip. Please excuse me for contacting you in English.

May I add your Bob extension to the [PopClip Extensions Directory][1]?

I have noticed that many PopClip users are typing "bob" in the filter box in the directory. I believe they are searching for this extension.

The advantages are:

- Easy for users to find the Bob extension.
- The extension will be signed so users will not get the "unsigned extension" warning.
- Directory will also link to Bob home page.

If you are willing, I can take a copy of your .popcipext and add it to my own repository (https://github.com/pilotmoon/PopClip-Extensions/), with credit to you in the README file.

I would like to rename it from "Bob v2" to simply "Bob" for consistency in the names of extensions in the directory. (The directory now has versions numbering built in so that versions can be identified.)

[1]:https://www.popclip.app/extensions/

**Comment by pilotmoon** [comment]
Alternatively, if you prefer, it is possible to keep the source code in this repo and you can add it the directory directly from here. This may be preferable, so as to have only one canonical source for the extension. In this case, I will tell you the instructions how to add it to the directory.

**Comment by ripperhe** [comment]
Hello, thank you for your advice, please tell me what I need to do.

Also, if I change the name from "Bob v2" to "Bob", I need to make some changes to Bob's documentation, so I'll tweak it together after I put it in the PopClip Extensions Directory.

**Comment by pilotmoon** [comment]
Great. I will send you the instructions shortly -- I need to write them! (Since this is a new feature foer my directory. You are the test subject :) )
I will also just sent pull request #10 with suggested update.

**Comment by pilotmoon** [comment]
Hello again, here are the instructions: https://gist.github.com/pilotmoon/0ec5661a4e48b99eeb803b91089748ca

For your repo the webhook URL will be:
`https://api.pilotmoon.com/webhooks/gh?include=source&versionPrefix=v`

You can tag for example `v3`.

Please tell me when you have done it, so I can check the submissions. Thanks!

**Comment by ripperhe** [comment]
Hello Nick, I have added webhook and added a new tag, thanks!

**Comment by pilotmoon** [comment]
Worked perfectly! 🎉 https://www.popclip.app/extensions/x/f59ba6

**Comment by ripperhe** [comment]
Amazing! 🎉

**Comment by pilotmoon** [comment]
Thank you for submitting the extension 🙏. I will close this issue.
